export const URL = 'http://localhost:8081/api'

export const EMPLOYEE = '/employee'
export const OPERATION = '/operation'
export const OUTPUT = '/output'
export const PRODUCT = '/product'
export const PRODUCT_GROUP = '/group'
export const UNIT = '/unit'
export const CLIENT = '/client'
export const PURCHASE = '/purchase'
export const TITLE = '/title'
export const BATCH = '/batch'
export const ACCEPTANCE = '/acceptance'
export const MOVEMENT = '/movement'
export const STOCK = '/stock'